pedevops/devops/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^$','login.views.home',),
    url(r'deletelog/$','devops.views.deletelog',name='deletelog'),
    url(r'onliestats/$','devops.views.onlinestats',name='onlinestats'),
    url(r'dns_update/update/$','devops.views.dns_update',name='dns_update'),
    url(r'dns_update/cancel/(?P<ID>\d+)/$','devops.views.dns_cancel',name='dns_cancel'),
    url(r'dns_update/apply/(?P<ID>\d+)/$','devops.views.dns_apply',name='dns_apply'),
    url(r'dns_check/$','devops.views.dns_check',name='dns_check'),
    url(r'proxy_update/update/$','devops.views.proxy_updates',name='proxy_update'),
    url(r'proxy_update/list/$','devops.views.proxy_updatelist',name='proxy_updatelist'),
    url(r'proxy_update/apply/(?P<ID>\d+)/$','devops.views.proxy_apply',name='proxy_apply'),
    url(r'proxy_update/cancel/(?P<ID>\d+)/$','devops.views.proxy_cancel',name='proxy_cancel'),
    url(r'proxy_update/okapply/(?P<ID>\d+)/$','devops.views.proxy_okapply',name='proxy_okapply'),
]

pedevops/login/urls.py
from django.conf.urls import include, url
urlpatterns = [
    url(r'^$','login.views.login',name='login'),
    url(r'^logout/$','login.views.logout',name='logout'),
    url(r'^admin/$','login.views.userlist',name='userlist'),
    url(r'^userdelete/(?P<ID>\d+)/$','login.views.userdelete',name='userdelete'),
    url(r'^useredit/(?P<ID>\d+)/$','login.views.useredit',name='useredit'),
    url(r'^role/$','login.views.rolelist',name='rolelist'),
    url(r'^roleedit/(?P<ID>\d+)/$','login.views.roleedit',name='roleedit'),
    url(r'permission/list/$','login.views.permissionlist',name='permissionlist'),
    url(r'permission/add/$','login.views.permissionadd',name='permissionadd'),
    url(r'permission/edit/(?P<ID>\d+)/$','login.views.permissionedit',name='permissionedit'),
    url(r'permission/delete/(?P<ID>\d+)/$','login.views.permissiondelete',name='permissiondelete'),
    url(r'permission/deny/$','login.views.permissiondeny',name='permissiondeny'),
]

pedevops/pedevops/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
#    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','login.views.home',name='home'),
    url(r'^login/',include('login.urls')),
    url(r'^devops/',include('devops.urls')),
    url(r'^pe/',include('pems.urls')),
    url(r'^zabbix/',include('zabbix.urls')),
    url(r'^coderelease/',include('coderelease.urls')),
]

pedevops/devops/models.py
#!/usr/bin/python
#coding: utf-8
from django.db import models

# Create your models here.

class deletelogapply(models.Model):
    username = models.CharField(max_length=64)
    email = models.EmailField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    log_host = models.CharField(max_length=128)
    log_path = models.CharField(max_length=255)
    save_date = models.PositiveSmallIntegerField()
    mark = models.CharField(max_length=255,null=True)
    status = models.PositiveSmallIntegerField()

class dns_updateapp(models.Model):
    dns_name = models.CharField(max_length=128)
    domain = models.CharField(max_length=64)
    record_type = models.CharField(max_length=8)
    analy_ip = models.CharField(max_length=128)
    update_ip = models.CharField(max_length=128,null=True,blank=True)
    operation_id = models.CharField(max_length=32)
    user = models.CharField(max_length=32)
    create_date = models.DateTimeField(auto_now_add=True)
    operation_date = models.CharField(max_length=32)
    server_reqinfo = models.CharField(max_length=255,null=True)
    status = models.PositiveSmallIntegerField()

    def __unicode__(self):
        return self.dns_name

class proxy_conf(models.Model):
    conf_file = models.CharField(max_length=128)

class proxy_domain(models.Model):
    dns = models.CharField(max_length=128)
    ip = models.CharField(max_length=255)
    modify_date = models.DateTimeField(auto_now_add=True)
    rollback = models.CharField(max_length=255,null=True,blank=True)
    mark = models.CharField(max_length=32,null=True)
    conf = models.ForeignKey(proxy_conf,related_name='proxyconf')

class proxy_update(models.Model):
    user = models.CharField(max_length=32)
    domain = models.CharField(max_length=128)
    mapping_ip = models.CharField(max_length=128)
    operation_date = models.CharField(max_length=32)
    reqinfo = models.CharField(max_length=32,null=True,blank=True)
    mark = models.CharField(max_length=255,null=True,blank=True)
    status = models.PositiveSmallIntegerField()

pedevops/devops/views.py
#!/usr/bin/python
#coding: utf-8
import os
import json
import datetime, time
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render
from form import deletelogform,dns_updateform,proxy_updateform
from devops_script import Deletelog
from models import deletelogapply,dns_updateapp,proxy_domain,proxy_update
from login.django_page import django_Page
from login.views import PermissionVerify,login_check
# Create your views here.


@PermissionVerify()
def deletelog(request):
    kwvars = login_check(request)
#    user = request.session.get('user')
#    if user:
#        user_roleid = request.session.get('user_roleid')
    if request.method == 'POST':
        form = deletelogform(request.POST)
        if form.is_valid():
            email = '%s@renren-inc.com' % kwvars['user']
            log_host = form.cleaned_data['log_host']
            log_path = form.cleaned_data['log_path']
            save_date = form.cleaned_data['save_date']
            try:
                cmd = 'rm %s' % log_path
                req = Deletelog.del_log(log_host,cmd,'deletelog')
            except Exception,e:
                reqs = '\n    %s' % e
                req = {'log_record':reqs,'code':1}
            else:
                mark = form.cleaned_data['mark']
                if req['code'] == 0:
                    status = 1
                else:
                    status = 2
                logdata = deletelogapply(username=kwvars['user'],email=email,log_host=log_host,log_path=log_path,save_date=save_date,mark=mark,status=status)
                logdata.save()
            my_json = json.dumps(req)
            return HttpResponse(my_json,content_type="application/json")
    else:
        form = deletelogform()
    kwvars['form'] = form
    return render(request,'devops/devops.deletelog.html',kwvars)
#    else:
#        return HttpResponseRedirect('/login')

def dns_updatetime():
    update_time = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    return update_time

@PermissionVerify()
def onlinestats(request):
    kwvars = login_check(request)
#    user = request.session.get('user')
#    if user:
#        user_roleid = request.session.get('user_roleid')
    if request.method == 'POST':
        strtime = request.POST['strdate']
        endtime = request.POST['endtate']
#            return HttpResponse(strtime)
    else:
        dates = datetime.datetime.now()
        endtime = dates.strftime('%Y-%m-%d')
        strtime = (dates - datetime.timedelta(days=7)).strftime('%Y-%m-%d')
    endtimes = '%s-23-59' % endtime
    strtimes = '%s-00-00' % strtime
    cmd = '/root/xiang.xiao3/dancer/project.py %s %s' % (strtimes,endtimes)
    proList = Deletelog.del_log('10.4.29.109',cmd,'onlinestats')
    proList = eval(proList['commd_out'])
    kwvars['strtime'] = strtime
    kwvars['endtime'] = endtime
    kwvars['proList'] = proList
    return render(request,'devops/devops.onlinestats.html',kwvars)
#    else:
#        return HttpResponseRedirect('/login')


@PermissionVerify()
def dns_check(request):
    kwvars = login_check(request)
#    user = request.session.get('user')
#    if user:
#        user_roleid = request.session.get('user_roleid')
#        kwvars = {'user':user,'user_roleid':user_roleid}
    if request.method == 'POST':
        dns_ip = request.POST['ip'].split(',')
        ip = {}
        for i in dns_ip:
            ip[i] = []
            dns_file = open('devops/devops_script/d.xiaonei.com','r')
            for d in dns_file.readlines():
                if i in d:
                    if i == d.split()[-1]:
                        dns_domain = '%s.d.xiaonei.com' % d.split()[0]
                        print dns_domain
                        ip[i].append(dns_domain)
            dns_file.close()
        if ip != {}:
            st_time = time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(os.stat("devops/devops_script/d.xiaonei.com").st_mtime))
            kwvars['st_time'] = st_time
            kwvars['ip'] = ip
    return render(request,'devops/devops.dns_check.html',kwvars)
#    else:
#        return HttpResponseRedirect('/login')


@PermissionVerify()
def dns_update(request):
    kwvars = login_check(request)
#    user = request.session.get('user')
#    if user:
#        user_roleid = request.session.get('user_roleid')
#        kwvars = {'user':user,'user_roleid':user_roleid}
    if request.method == 'POST':
        req_dict = {}
        dns_name = request.POST.getlist('dns_name')
        domain = request.POST.getlist('domain')
        operation_id = request.POST.getlist('operation_id')
        record_type = request.POST.getlist('record_type')
        analy_ip = request.POST.getlist('analy_ip')
        for dom in dns_name:
            dom_index = dns_name.index(dom)
            if dom !='' and analy_ip[dom_index] != '':
                req_dom = 'req_%s' % dom_index
                req_dict[req_dom] = [operation_id[dom_index],dns_name[dom_index],domain[dom_index],record_type[dom_index],analy_ip[dom_index]]
            elif dom == '' and analy_ip[dom_index] == '':
                pass
            else:
                kwvars['updatereq'] = '您的输入有误,请检查DNS名称或IP地址输入是否正确.谢谢!'

        if len(req_dict) == 0 and len(kwvars) == 0:
            kwvars['updatereq'] = '请填写需要操作的DNS信息后提交.谢谢!'
        else:
            uptime = dns_updatetime()
            for db in req_dict.values():
                #dns_names = '%s.%s' % (db[1], db[2])
                dns_updateapp.objects.create(dns_name=db[1],domain=db[2],record_type=db[3],analy_ip=db[4],operation_id=db[0],user=kwvars['user'],operation_date=uptime,status=1)
                kwvars['updatereq'] = '提交成功,请等待管理员操作.谢谢!'
        return render(request,'devops/devops.dns_req.html',kwvars)
    if kwvars['user_roleid'] == 1:
        dnslist = dns_updateapp.objects.order_by('-id')[:100]
    else:
        dnslist = dns_updateapp.objects.filter(user = kwvars['user']).order_by('-id')
    form = dns_updateform()
    kwvars['form'] = form
    kwvars['ranges'] = range(1,4)
    kwvars['dnslist'] = dnslist
    return render(request,'devops/devops.dns_update.html',kwvars)
#else:
#        return HttpResponseRedirect('/login')

@PermissionVerify()
def dns_cancel(request,ID):
    kwvars = login_check(request)
#    user = request.session.get('user')
#    if user:
#        user_roleid = request.session.get('user_roleid')
#        kwvars = {'user':user,'user_roleid':user_roleid}
    if kwvars['user_roleid'] == 1:
        reqinfo = request.POST['reqinfo']
        stats = 5
    else:
        reqinfo = '用户取消'
        stats = 4
    uptime = dns_updatetime()
    dns_updateapp.objects.filter(id = ID).update(operation_date=uptime,status=stats,server_reqinfo=reqinfo)

    return HttpResponseRedirect(reverse('dns_update'))
#    else:
#        return HttpResponseRedirect('/login')


@PermissionVerify()
def dns_apply(request,ID):
    kwvars = login_check(request)
#    user = request.session.get('user')
#    if user:
#        user_roleid = request.session.get('user_roleid')
    if kwvars['user_roleid'] ==1:
        uptime = dns_updatetime()
        dns_updateapp.objects.filter(id = ID).update(operation_date=uptime,status = 2)

        return HttpResponseRedirect(reverse('dns_update'))
#    else:
#        return HttpResponseRedirect('/login')


@PermissionVerify()
def proxy_updates(request):
    kwvars = login_check(request)
#    user = request.session.get('user')
#    if user:
#        user_roleid = request.session.get('user_roleid')
#        kwvars = {'user':user,'user_roleid':user_roleid}
    if request.method == 'POST':
        if 'domain_check' in request.POST:
            domaincheck_list = request.POST['domain_check'].split(',')
            domaincheck = {}
            for i in domaincheck_list:
                domaininfo = proxy_domain.objects.filter(dns=i,mark='').values('ip','conf_id')
                print domaininfo
                domaindic,relationlist = {},[]
                if len(domaininfo) != 0:
                    domains = domaininfo[0]['ip'].split(',')
                    for d in domains:
                        domains[domains.index(d)] = d.split()[0]
                    relationid = int(domaininfo[0]['conf_id'])
                    print relationid
                    relation = proxy_domain.objects.filter(conf_id=relationid,mark='').values('dns')
                    for r in relation:
                        relationlist.append(r['dns'])
                    domaindic['ip'] = domains
                    domaindic['relation'] = relationlist
                domaincheck[i] = domaindic
            if domaincheck != {}:
                kwvars['domain_check'] = domaincheck
                print domaincheck
        else:
            form = proxy_updateform(request.POST)
            req = {'code':1}
            if form.is_valid():
                domain = form.cleaned_data['domain']
                mapping_ip = form.cleaned_data['mapping_ip']
                mark = form.cleaned_data['mark']
                operation_date = dns_updatetime()
                try:
                    proxy_update.objects.create(user=kwvars['user'],domain=domain,mapping_ip=mapping_ip,operation_date=operation_date,mark=mark,status=1)
                except Exception,e:
                    req['reqinfo'] = '\n    %s' % e
                else:
                    req['code'] = 0
                my_json = json.dumps(req)
                return HttpResponse(my_json,content_type="application/json")
    kwvars['form'] = proxy_updateform()
    return render(request,'devops/devops.proxy_update.html',kwvars)
#    else:
#        return HttpResponseRedirect('/login')

@PermissionVerify()
def proxy_updatelist(request):
    kwvars = login_check(request)
#    user = request.session.get('user')
#    if user:
#        user_roleid = request.session.get('user_roleid')
#        kwvars = {'user':user,'user_roleid':user_roleid}
    if kwvars['user_roleid'] == 1:

pedevops/templates/devops/devops.deletelog.html
{% extends "common/base.devops.html" %}

{% block title %}
    Delete log
{% endblock %}

{% block rcontent %}
    <div class="btn-toolbar">
        <div class="btn-group">
            {% url "deletelog" as deletelogurl %}
            <a class="btn btn-default {%if request.path = deletelogurl%} active {%endif%}" href={{ deletelogurl }}><span class="glyphicon glyphicon-edit"></span>LOG删除</a>
        </div>
    </div>

    <hr/>
           <div class="alert alert-info">
                    注:
                    日志删除操作后端使用web用户(注意权限)调用find命令:<font color="#FF0000">find %s -name '*log*' -size +5M -mtime +%s | xargs rm -f </font><br />
                      &nbsp&nbsp&nbsp&nbsp&nbsp操作时请务必小心,如有疑问请发邮件至renren.pe@renren-inc.com。
               <p href="#" data-dismiss="alert" class="close">X</a>
         </div>
    <br />
    <br />
    <form class="form-horizontal" id="myform" onsubmit="return false" role="form" action={% url "deletelog" %} method="POST" >
    {% csrf_token %}

        {% for item in form %}
            <div class="form-group">
                <label class="control-label col-md-2">{{item.label}}</label>
                <div class="col-md-7">
                    {{item}}
                </div>
                <div class="col-md-offset-1 col-md-10">
                    {{item.errors}} 
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <br />
            <div class="col-md-offset-4 col-md-10">
                <input type="submit" class="btn btn-danger btn-sm" onclick="subm()" value="执行删除">
            <div>
        </div>
    </form> 
<script LANGUAGE="javascript">

function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);

            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');
function csrfSafeMethod(method) {
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

function subm(){
    if(confirm('确认删除吗？'))
        var log_host = $("#id_log_host").val();
        var log_path = $("#id_log_path").val();
        var save_date = $("#id_save_date").val();
        var mark = $("#id_mark").val();
//        var url = $("form").attr("action");
//        var data = $("form").serialize();
//        $.post(url,data,function(req){
//            alert(req.text);
//        });
        var mydata = {
            'log_host':log_host,
            'log_path':log_path,
            'save_date':save_date,
            'mark':mark,
        };
        $.ajax({
            type:"POST",
            data:mydata,
            url:"http://pedevops.d.xiaonei.com:8001/devops/deletelog/",
            dataType:"json",
            success:function(data){
                if(data.code==0){
                    var log_record = '命令执行成功,详情如下:'+data.log_record;
                    alert(log_record);
                }else{
                    var log_record = '命令执行失败,详情如下:'+data.log_record;
                    alert(log_record);
                }
            },
            error:function(data){
            }
        });

};

</script>
{% endblock %}

pedevops/templates/devops/devops.dns_check.html
{% extends "common/base.devops.html" %}

{% block title %}
     dns_check
{% endblock %}

{% block rcontent %}
    <div class="btn-toolbar">
        <div class="btn-group">
            {% url "dns_check" as dns_checkurl %}
            <a class="btn btn-default {% if request.path = dns_checkurl %} active {%endif%}" href={{ dns_checkurl }}><span class="glyphicon glyphicon-edit"></span>内网DNS反向查询</a>
        </div>
    </div>

    <hr/>
             <div class="alert alert-info">
                    注:
                    公司内网DNS查询(d.xiaonei.com)。有疑问请发邮件至pe.renren@renren-inc.com.
               <p href="#" data-dismiss="alert" class="close">X</p>
         </div>
    <br />
    <div>
            <form class="form-horizontal" id="myform" role="form" action={% url "dns_check" %} method="POST" >
                {% csrf_token %}
                 <br />
                 <div class="form-group">
                     <label class="control-label col-md-1">IP地址</label>
                     <div class="col-md-9">                     
                         <input class="form-control" type="text" name="ip" value="" placeholder="请输入ip地址,多个请用','号隔开" />
                     </div>
                 </div>
                 <br />
                 <div class="form-group">
                    <div class="col-md-offset-4 col-md-10">
                        <button type="submit" class="btn btn-danger btn-sm">查询</button>
                    </div>
                </div>
            </form>
    </div>
    <div class="btn-toolbar">
       {% if ip %}
           <div class="page-header">
               <h3>查询结果:</h3>
           </div>
                <table class="table table-hover table-striped  table-bordered table-condensed" style="table-layout:fixed; word-break:break-all; word-wrap:break-all;">
                <tr>
                    <th width="30%">IP Address</th>
                    <th>Domain Name</th>
                </tr>
                {% for k,v in ip.items %}
                    <tr>
                         <td> {{ k }} </td>
                         <td>
                             {% for i in v %}
                                 {{i}}<br/>
                             {% endfor %}
                         </td>
                    </tr>

                {% endfor %}
                </table>
           <div>
               <font color="#FF0000">注: DNS最后一次同步时间为:{{ st_time }}</font>
           </div>
       {% endif %}
       
    </div>
    
</div>

{% endblock %}

pedevops/templates/devops/devops.dns_req.html
<html>
    <head>
          <title>人人运维</title>
    </head>

{% block rcontent %}
    <body>
          <br/>
          <br/>
          <br/>
          <p align="center">{{ updatereq }}</p>
          <p align="center">3秒后返回</p>
          <meta http-equiv="refresh" content="3;url={% url "dns_update" %}">
    </body>
{% endblock%}
</html>

pedevops/templates/devops/devops.onlinestats.html
{% extends "common/base.devops.html" %}

{% block title %}
    G_onlin stats
{% endblock %}

{% block rcontent %}
    <div class="btn-toolbar">
        <div class="btn-group">
            {% url "onlinestats" as onlinestatsurl %}
            <a class="btn btn-default {% if request.path = onlinestatsurl %} active {%endif%}" href={{ onlinestatsurl }}><span class="glyphicon glyphicon-edit"></span>上线统计查询</a>
        </div>
    </div>

    <hr/>
             <div class="alert alert-info">
                    注:
                    业务上线及版本统计查询。有疑问请发邮件至pe.renren@renren-inc.com.
               <p href="#" data-dismiss="alert" class="close">X</p>
         </div>
    <br />

     <div class="widget-content nopadding">

          <form id="myform" action={% url "onlinestats" %} method="post" class="form-horizontal" role="form">
               {% csrf_token %}
               <div class="btn-group">
                         <pre>开始日期: <input id="strdate" type="text" name="strdate" value={{ strtime }} >    结束日期: <input id="endtate" name="endtate" type="text" value={{ endtime }} >    <input type="submit" class="btn btn-primary btn-sm" value="查询"></pre>
               </div>
          </form>
          <br />
          <table class="table table-hover table-striped  table-bordered table-condensed" style="table-layout:fixed; word-break:break-all; word-wrap:break-all;">
           <tr>
             <th width="20%">平台</th>
             <th width="20%">业务</th>
             <th width="15%">统计数</th>
             <th width="45%">版本号</th>
           </tr>
             
            {% for k,v in proList.items %}
                 {% for s,d in v.items %}
                     <tr style="font-size:13px;">
                         <td width="20%">{{ k }}</td>
                         <td width="20%">{{ s }}</td>
                         <td width="15%">{{ d.0 }}</td>
                         <td width="45%">{{ d.1 }}</td>
                     </tr>
                 {% endfor %}
            {% endfor %}
         </table>
</div>

<script LANGUAGE="javascript">
//function subm(){
//    var url = 'http://10.5.11.17:8000/devops/onliestats/';
//    var data = $("form").serialize();
//    $.post(url,data,function(req){
//        alert(req);
    });
}
</script>

{% endblock %}

pedevops/templates/devops/devops.proxy_update.html
{% extends "common/base.devops.html" %}

{% block title %}
     Proxy_update
{% endblock %}

{% block rcontent %}
    <div class="btn-toolbar">
        <div class="btn-group">
            {% url "proxy_update" as proxy_updateurl %}
            <a class="btn btn-default {% if request.path = proxy_updateurl %} active {%endif%}" href={{ proxy_updateurl }}><span class="glyphicon glyphicon-edit"></span>代理层操作申请</a>
            {% url "proxy_updatelist" as proxy_updatelisturl %}
            <a class="btn btn-default {%if request.path = proxy_updatelisturl%} active {%endif%}" href={{ proxy_updatelisturl }}><span class="glyphicon glyphicon-list"></span>代理层申请列表</a>
        </div>
    </div>

    <hr/>
             <div class="alert alert-info">
                    注:<br />
                    &nbsp&nbsp&nbsp&nbsp&nbsp<font color="#FF0000">提交操作申请前请查询是否有关联域名。如有，请确认是否同时修改.如确认请在"域名"选项中写入所有关联域名,否则请在操作说明选项中注明。</font>
                    <br />&nbsp&nbsp&nbsp&nbsp&nbsp如无关联域名或新加入代理层的域名请忽略。有疑问请发邮件至pe.renren@renren-inc.com.谢谢!
               <p href="#" data-dismiss="alert" class="close">X</p>
         </div>

     <div>
            <div class="btn-group">
            <a class="btn btn-primary btn-3g">代理层后端查询   <span class="glyphicon glyphicon-list"></span></a>
            </div>
            <br/>
            <form class="form-horizontal" id="myform" role="form" action={% url "proxy_update" %} method="POST" >
                {% csrf_token %}
                 <br />
                 <div class="col-lg-16" style="padding: 1px 100px 1px;">
                 <div class="btn-group">

                  <pre>域名: <input id="strdate" style="width:320px;" type="text" name="domain_check" value=""  placeholder="请输入需要查询的域名,多个请用','号隔开" > <input type="submit" class="btn btn-danger btn-sm" value="查询"></pre
>
                </div>
                </div>
            </form>
   </div>
   <div class="btn-toolbar" style="padding: 1px 100px 1px;">
        {% if domain_check %}
                <table class="table table-hover table-striped  table-bordered table-condensed" style="table-layout:fixed; word-break
:break-all; word-wrap:break-all;">
                <tr>
                    <th width="30%">Domain Name</th>
                    <th>IP Address</th>
                    <th>关联域名</th>
                </tr>
                {% for k,v in domain_check.items %}
                    <tr>
                        <td> {{ k }} </td>
                        <td>
                            {% for i in v.ip %}
                                {{ i }} <br />
                            {% endfor %}
                        </td>
                        <td>
                            {% for r in v.relation %}
                                {{ r }} <br />
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor%}

                </table>
        {% endif %}
   </div>
   <br />
   <div class="btn-group">
         <a class="btn btn-primary btn-3g">代理层操作申请   <span class="glyphicon glyphicon-list"></span></a>
   </div>
   <br />
   <br />
       <form id="myform" onsubmit="return false" class="form-horizontal" role="form" action={% url "proxy_update" %} method="POST" >
    {% csrf_token %}

        {% for item in form %}
            <div class="form-group">
                <label class="control-label col-md-2">{{item.label}}</label>
                <div class="col-md-7">
                    {{item}}
                </div>
                <div class="col-md-offset-1 col-md-10">
                    {{item.errors}}
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <br />
            <div class="col-md-offset-4 col-md-10">
               <input type="submit" class="btn btn-danger btn-sm" onclick="modify()" value="确认提交">
            <div>
        </div>
    </form>
</div>

<script>
//$.ajaxSetup({
//  data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
//});

function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);

            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

var csrftoken = getCookie('csrftoken');
function csrfSafeMethod(method) {
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

function modify(){
    if(confirm('确认修改代理层?')){
        var domain = $("#id_domain").val();
        var mapping_ip = $("#id_mapping_ip").val();
        var mark = $("#id_mark").val();
        var url = $("myform").attr("action");
        var data = {
            'domain':domain,
            'mapping_ip':mapping_ip,
            'mark':mark,
        };
        $.post(url,data,function(result){
            if(result.code==0){
                alert('申请成功,等待管理员审批(详情请查询申请列表)!');
            }else{
                var reqerr = '申请失败,详情如下:' + result.reqinfo;
                alert(reqerr);
            }
        });
    };
}


</script>
{% endblock %}

pedevops/templates/devops/page.html
test